import { ready } from "@/lib/db";
import type { SpamAssessment } from "./spam";

/**
 * Google disavow file generation.
 *
 * Read this before shipping a disavow file, because it is the one genuinely
 * destructive action in this whole tool:
 *
 *  - A disavow tells Google to ignore links. There is no undo that takes
 *    effect quickly; recovery means re-uploading and waiting for a recrawl.
 *  - Google's own guidance is that most sites should never need one. Their
 *    spam systems already discount obvious junk links, so disavowing random
 *    low-quality links is usually a no-op at best.
 *  - It is genuinely warranted in two cases: you have a manual action for
 *    unnatural links, or you know links were bought/built manipulatively and
 *    you want to disclaim them before they are actioned.
 *
 * So this module ships an entry-by-entry justification with every file, and
 * defaults to domain-level entries (`domain:example.com`), which is what Google
 * recommends since a spam domain rarely has one bad page.
 */

export interface DisavowEntry {
  scope: "domain" | "url";
  value: string;
  reason: string;
  spamScore: number;
}

export interface DisavowFile {
  content: string;
  entries: DisavowEntry[];
  stats: {
    domains: number;
    urls: number;
    /** Referring domains considered but deliberately excluded. */
    excluded: number;
  };
}

export interface DisavowOptions {
  /** Minimum spam score to include. Default 70 (the "toxic" band). */
  minScore?: number;
  /** Include domains the scorer marked "review" as well. Default false. */
  includeReview?: boolean;
  /** Domains to never disavow regardless of score. */
  allowlist?: string[];
}

export function buildDisavow(
  assessments: SpamAssessment[],
  opts: DisavowOptions = {},
): DisavowFile {
  const minScore = opts.minScore ?? 70;
  const allow = new Set((opts.allowlist ?? []).map((d) => d.toLowerCase()));

  const entries: DisavowEntry[] = [];
  let excluded = 0;

  for (const a of assessments) {
    if (allow.has(a.domain.toLowerCase())) {
      excluded++;
      continue;
    }
    const qualifies =
      a.recommendation === "disavow" ||
      (opts.includeReview && a.recommendation === "review");

    if (!qualifies || a.score < minScore) {
      excluded++;
      continue;
    }

    const topSignals = a.signals
      .filter((s) => s.weight > 0)
      .slice(0, 3)
      .map((s) => s.label)
      .join("; ");

    entries.push({
      scope: "domain",
      value: a.domain,
      reason: `score ${a.score} — ${topSignals}`,
      spamScore: a.score,
    });
  }

  entries.sort((a, b) => b.spamScore - a.spamScore);

  const now = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    `# Disavow file generated by LinkForge on ${now}`,
    `# ${entries.length} domain(s) at spam score >= ${minScore}.`,
    "#",
    "# Every entry below is annotated with the signals that triggered it.",
    "# Review each one before uploading. Remove any line you cannot justify:",
    "# disavowing a legitimate link throws away ranking value for no reason.",
    "#",
    "# Upload at: https://search.google.com/search-console/disavow-links",
    "",
  ];

  for (const e of entries) {
    lines.push(`# ${e.reason}`);
    lines.push(e.scope === "domain" ? `domain:${e.value}` : e.value);
  }

  return {
    content: `${lines.join("\n")}\n`,
    entries,
    stats: {
      domains: entries.filter((e) => e.scope === "domain").length,
      urls: entries.filter((e) => e.scope === "url").length,
      excluded,
    },
  };
}

/** Records what was exported, so the next run can show what changed. */
export function persistDisavow(entries: DisavowEntry[]): void {
  const conn = ready();
  const stmt = conn.prepare(
    `INSERT INTO disavow_entries (scope, value, reason, spam_score, exported_at, active)
     VALUES (?, ?, ?, ?, datetime('now'), 1)
     ON CONFLICT (scope, value) DO UPDATE SET
       reason = excluded.reason,
       spam_score = excluded.spam_score,
       exported_at = excluded.exported_at,
       active = 1`,
  );
  conn.transaction(() => {
    for (const e of entries) stmt.run(e.scope, e.value, e.reason, e.spamScore);
  })();
}

export function previouslyDisavowed(): Set<string> {
  const rows = ready()
    .prepare<[], { value: string }>(
      "SELECT value FROM disavow_entries WHERE active = 1 AND scope = 'domain'",
    )
    .all();
  return new Set(rows.map((r) => r.value));
}
